apiVersion: v1
kind: Pod
metadata:
   name: allergy-service
   labels:
     app: allergy-service
spec:
  containers:
    - name: allergy-service
      image: jasdhirinrevature/allergy-svc:latest 
      ports:
        - containerPort: 8082
     
